CC = gcc
EXECUTABLES = simpletest1

LIBDIR = 
LIBS = 
CFLAGS = -g -Wall

default: all

all: 
	$(CC) $(CFLAGS) $(EXECUTABLES)

clean:
	rm -f core $(EXECUTABLES) a.out

my_malloc.o: my_malloc.c my_malloc.h
	$(CC) $(CFLAGS) -c my_malloc.c

my_malloc_nocompact.o: my_malloc.c my_malloc.h
	$(CC) $(CFLAGS) -c -DNO_COALESCE -o my_malloc_nocompact.o my_malloc.c

simpletest1: simpletest1.c my_malloc.o my_malloc.h
	$(CC) $(CFLAGS) -o simpletest1 simpletest1.c my_malloc.o $(LIBS)

simpletest2: simpletest2.c my_malloc.o my_malloc.h
	$(CC) $(CFLAGS) -o simpletest2 simpletest2.c my_malloc.o $(LIBS)

testnocompact: testnocompact.c my_malloc_nocompact.o my_malloc.h
	$(CC) $(CFLAGS) -o testnocompact testnocompact.c my_malloc_nocompact.o $(LIBS)

testmymalloc: testmymalloc.c my_malloc.o my_malloc.h
	$(CC) $(CFLAGS) -o testmymalloc testmymalloc.c my_malloc.o $(LIBS)